# Generated by Django 5.1.5 on 2025-06-13 20:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=8)),
                ('date', models.DateField()),
                ('startTime', models.DateTimeField(null=True)),
                ('endTime', models.DateTimeField(null=True)),
                ('playTime', models.TimeField(null=True)),
                ('turn', models.IntegerField(default=1)),
                ('dice2', models.IntegerField(default=0)),
                ('dice3', models.IntegerField(default=0)),
                ('dice4', models.IntegerField(default=0)),
                ('dice5', models.IntegerField(default=0)),
                ('dice6', models.IntegerField(default=0)),
                ('dice7', models.IntegerField(default=0)),
                ('dice8', models.IntegerField(default=0)),
                ('dice9', models.IntegerField(default=0)),
                ('dice10', models.IntegerField(default=0)),
                ('dice11', models.IntegerField(default=0)),
                ('dice12', models.IntegerField(default=0)),
                ('recentDice1', models.IntegerField(null=True)),
                ('recentDice2', models.IntegerField(null=True)),
                ('recentDice3', models.IntegerField(null=True)),
                ('recentDice4', models.IntegerField(null=True)),
                ('recentDice5', models.IntegerField(null=True)),
                ('recentDice6', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=8)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('birthday', models.DateField()),
                ('icon', models.ImageField(default='icons/default_icon.png', upload_to='icons/')),
                ('role', models.IntegerField(default=1)),
                ('isGraduated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('win', models.BooleanField(default=False)),
                ('order', models.IntegerField()),
                ('color', models.CharField(max_length=8)),
                ('dice2', models.IntegerField(default=0)),
                ('dice3', models.IntegerField(default=0)),
                ('dice4', models.IntegerField(default=0)),
                ('dice5', models.IntegerField(default=0)),
                ('dice6', models.IntegerField(default=0)),
                ('dice7', models.IntegerField(default=0)),
                ('dice8', models.IntegerField(default=0)),
                ('dice9', models.IntegerField(default=0)),
                ('dice10', models.IntegerField(default=0)),
                ('dice11', models.IntegerField(default=0)),
                ('dice12', models.IntegerField(default=0)),
                ('point', models.IntegerField(default=0)),
                ('longestRoad', models.BooleanField(default=False)),
                ('largestArmy', models.BooleanField(default=False)),
                ('halfPoint', models.IntegerField(default=0)),
                ('yellowFriend', models.BooleanField(default=False)),
                ('greenFriend', models.BooleanField(default=False)),
                ('readFriend', models.BooleanField(default=False)),
                ('blueFriend', models.BooleanField(default=False)),
                ('merchant', models.BooleanField(default=False)),
                ('saviourPoint', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catan.gameresult')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catan.player')),
            ],
        ),
    ]
